### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by earl** [jayyvis/node-beanstalkc#1]
May I humbly suggest using a slightly different name for your client library?

[beanstalkc](https://github.com/earl/beanstalkc) is already in use for a [fairly popular](https://pypi.python.org/pypi/beanstalkc) beanstalkd client library for Python. It would be great, if we could avoid the future confusion from having two distinct projects using the same name.

No offence intended, it is a fairly obvious name :) Given that your project is still very young, I hope that renaming it should not be too big a problem -- I think it would be in the interest of both of our existing and future users.

**Comment by jayyvis** [comment]
I am a long time user of python beanstalkc and it's simplicity had inspired me always (wrote [beanshell](https://github.com/jayyvis/beanshell) using it). And since I looked for a similar library in node.js, we're here :-)

I thought that's for python and this one for nodejs. Still, as you said it may lead to confusion. I should have reached you upfront and I'm sorry for not doing that. 

Sure, I'll rename this. Do you think node-beanstalkc should be fine?

**Comment by earl** [comment]
Yes, I think node-beanstalkc should be ok.

**Comment by jayyvis** [comment]
It's done!
